on:
  pull_request:
    paths: ["src/**"]
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/changelog-reminder-action@v2